### ISSUE TITLE
没有sql脚本啊

### ISSUE THREAD

**Issue by lin666999** [schuanhe/Plook#2]
怎么搞

**Comment by big-tooth** [comment]
> 怎么搞

没意义，我把这个项目fork下来改的老血都快吐出来了

**Comment by schuanhe** [comment]
eee,我还没写完勒






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月9日(星期二) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [schuanhe/Plook] 没有sql脚本啊 (Issue #2)





  
怎么搞
  
没意义，我把这个项目fork下来改的老血都快吐出来了

**Comment by schuanhe** [comment]
> 怎么搞
后面写好了会加上

**Comment by schuanhe** [comment]
现在不用sql也可以运行，切换到nodb分支

**Comment by schuanhe** [comment]
等待v2
